-- Initialize English Teaching AI Database

-- Insert Sample Users
INSERT INTO users (email, name, avatar, level, created_at, updated_at) VALUES 
('john@example.com', 'John Doe', 'https://example.com/avatar1.jpg', 'BEGINNER', NOW(), NOW()),
('jane@example.com', 'Jane Smith', 'https://example.com/avatar2.jpg', 'INTERMEDIATE', NOW(), NOW()),
('bob@example.com', 'Bob Wilson', 'https://example.com/avatar3.jpg', 'ADVANCED', NOW(), NOW());

-- Insert Sample Conversations
INSERT INTO conversations (id, user_id, title, created_at, updated_at) VALUES 
('conv_1717716240000_conversation1', 1, 'Conversation - 2024-06-06', NOW(), NOW()),
('conv_1717716250000_conversation2', 2, 'Conversation - 2024-06-06', NOW(), NOW());

-- Insert Sample Vocabulary Words
INSERT INTO vocabulary_words (word, meaning, difficulty, pronunciation, part_of_speech, created_at) VALUES 
('eloquent', 'Fluent and persuasive in speech', 'ADVANCED', 'EL-uh-kwunt', 'ADJECTIVE', NOW()),
('communicate', 'Share or exchange information', 'INTERMEDIATE', 'kuh-MYOO-ni-kayt', 'VERB', NOW()),
('ambiguous', 'Open to more than one interpretation', 'ADVANCED', 'am-BIG-yoo-us', 'ADJECTIVE', NOW()),
('pragmatic', 'Dealing with things in a practical way', 'ADVANCED', 'prag-MA-tik', 'ADJECTIVE', NOW()),
('facilitate', 'Make it easier for something to happen', 'INTERMEDIATE', 'fuh-SIL-i-tayt', 'VERB', NOW()),
('meticulous', 'Showing great attention to detail', 'ADVANCED', 'muh-TIK-yuh-lus', 'ADJECTIVE', NOW()),
('resilient', 'Able to recover quickly', 'INTERMEDIATE', 'rih-ZIL-yunt', 'ADJECTIVE', NOW()),
('thrive', 'Grow or develop in a healthy way', 'INTERMEDIATE', 'thriv', 'VERB', NOW());

-- Insert Sample Speaking Scenarios
INSERT INTO speaking_scenarios (title, description, context, difficulty, topic, estimated_duration) VALUES 
('Job Interview', 'Practice a job interview scenario', 'Interviewing for a software engineer position', 'INTERMEDIATE', 'Professional Communication', 600),
('Business Meeting', 'Participate in a business meeting', 'Presenting project updates to stakeholders', 'ADVANCED', 'Professional Communication', 900),
('Restaurant Order', 'Order food at a restaurant', 'In a casual dining environment', 'BEGINNER', 'Daily Life', 300),
('Hotel Booking', 'Book a hotel room', 'Discussing amenities and rates', 'BEGINNER', 'Travel', 300),
('Emergency Situation', 'Handle an emergency phone call', 'Reporting an accident or emergency', 'ADVANCED', 'Critical Situations', 600);

-- Insert Sample Achievements
INSERT INTO achievements (title, description, badge) VALUES 
('First Steps', 'Complete your first chat session', '🌟'),
('Grammar Master', 'Complete 50 grammar corrections', '📚'),
('Pronunciation Pro', 'Achieve 90% score in 10 speaking sessions', '🎤'),
('Vocabulary Virtuoso', 'Learn 100 vocabulary words', '📖'),
('Week Warrior', 'Maintain a 7-day learning streak', '🔥'),
('Month Maven', 'Maintain a 30-day learning streak', '🏆'),
('Professional Speaker', 'Complete all professional scenarios', '💼'),
('Fluency Champion', 'Achieve overall fluency score of 90%', '⭐');

-- Insert Sample Skill Stats (optional)
-- This would typically be generated by user activity
INSERT INTO skill_stats (user_id, skill_name, score, level, trend, improvement) VALUES 
(1, 'GRAMMAR', 75.5, 'INTERMEDIATE', 'IMPROVING', 5.2),
(1, 'PRONUNCIATION', 68.0, 'BEGINNER', 'STABLE', 2.1),
(1, 'VOCABULARY', 70.0, 'BEGINNER', 'IMPROVING', 3.5),
(1, 'FLUENCY', 65.0, 'BEGINNER', 'STABLE', 1.0),
(2, 'GRAMMAR', 85.5, 'ADVANCED', 'IMPROVING', 2.1),
(2, 'PRONUNCIATION', 82.0, 'ADVANCED', 'STABLE', 0.5);

-- Insert Sample Messages (optional)
INSERT INTO messages (user_id, conversation_id, content, sender, timestamp) VALUES 
(1, 'conv_1717716240000_conversation1', 'How can I improve my English pronunciation?', 'USER', NOW()),
(1, 'conv_1717716240000_conversation1', 'To improve your pronunciation, you should practice speaking regularly and listen to native speakers.', 'AI', NOW());

-- Insert Sample Daily Stats (optional)
INSERT INTO daily_stats (user_id, date, overall_score, message_count, voice_count, grammar_corrections_count, pronunciation_score, new_words_learned, session_duration, current_streak) VALUES 
(1, CURRENT_DATE, 72.5, 15, 3, 5, 70.0, 2, 1800, 5),
(2, CURRENT_DATE, 78.0, 20, 5, 8, 80.0, 3, 2400, 10);

-- Example queries to verify data
SELECT * FROM users;
SELECT * FROM vocabulary_words;
SELECT * FROM speaking_scenarios;
SELECT * FROM achievements;
