name: Spring Boot CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

env:
  APP_NAME: Spring-Boot-App
  APP_ENV: DEV

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Print Environment Variables
        run: |
          echo "Application Name: $APP_NAME"
          echo "Environment: $APP_ENV"

      - name: Verify Secret Exists
        env:
          DEMO_SECRET: ${{ secrets.DEMO_SECRET }}
        run: |
          echo "Secret loaded successfully"

      - name: Build Application
        run: mvn clean package

      - name: Run Unit Tests
        run: mvn test
      
      - name: SonarQube Analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn clean verify sonar:sonar \
           -Dsonar.token=${SONAR_TOKEN}
          echo "sonar loaded successfully"
      - name: Show Build Output
        run: |
          find . -name "*.jar"

      - name: Upload JAR Artifact
        uses: actions/upload-artifact@v4
        with:
          name: spring-boot-artifact
          path: |
            **/target/*.jar
            **/target/*.war